### ISSUE TITLE
Munkalap lista szűrése állapot szerint

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#13]
A munkalap lista oldalon a lista fölött legyen egy állapotszűrő, amivel a kövezkető állapotokat lehet kiválasztani:

- nyitott
- készre jelentett
- lezárt
- rontott

### Acceptance criteria
A munkalap lista a szűrésnek megfelelően változik.

**Comment by VicziTomi** [comment]
Note: nincs rontott státuszunk
