### ISSUE TITLE
Munkalap nyomtatása

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#15]
A kész és lezárt munkalapot lehessen nyomtatni. Ehhez a munkalap listában és a munkalap oldalán legyen egy gomb.

A nyomtatási kép generálása két megoldást látunk:
1. frontend oldalon egy külön nyomtatásra optimalizált oldal, ami az adatokból mindig dinamikusan generált (CSS @media print)
2. backend oldalon generálunk egy PDF-et lezáráskor, amit elmentünk a szerveroldalon és bármikor letölthető

TBD @borosr @VicziTomi

**Comment by borosr** [comment]
Oké, akkor ha jól értem ez egyelőre tárgytalan backend oldalról, igaz?

**Comment by 6uliver** [comment]
Kicsit elfogult vagyok, mert van benne néhány sor kódom, de ezt használtam és sokkal magasabb szintű, mint a jsPDF alapból: https://github.com/bpampuch/pdfmake

Tud táblázatokat meg automatán tördeli a sorokat stb.
