### ISSUE TITLE
FIX: munkalap leírása BE

### ISSUE THREAD

**Issue by VicziTomi** [flowacademyhu/iota-munkalap#169]
Backendnek képesnek kell lennie hosszú szöveg kezelésére, max. 3000 karakter.

**Comment by borosr** [comment]
Legyen `@Lob`, az elvileg megoldja, igazoljátok integrációs tesztekkel.

**Comment by gyanyim** [comment]
@borosr A Lob nem oldotta meg ezt a helyzetet, viszont ennyi elég volt neki: @Column(name = "custom_type_of_work", length = 3000)

**Comment by borosr** [comment]
Ez sem rossz. De megnéznéd kérlek, hogy milyen SQL típussá fordul így le?

**Comment by gyanyim** [comment]
@borosr A H2-ben azt írja: VARCHAR(3000)

**Comment by borosr** [comment]
Oké, legyen akkor így!
