### ISSUE TITLE
FIX: munkalap sorszáma

### ISSUE THREAD

**Issue by VicziTomi** [flowacademyhu/iota-munkalap#170]
Vegyél fel egy új adattagot a munkalaphoz, amely a munkalap sorszámát fogja jelölni.
Kritériumok a sorszám generálással kapcsolatban:
- szigorúan monoton növekvő
- léptetés egysége: 1
- kezdő érték: 10000
- prefix minden sorszámhoz: M-

Tehát egy munkalap sorszám így néz ki pl.: M-10123

**Comment by borosr** [comment]
Kell rá egy sekvencia, a `@GeneratedValue`-val meg tudjátok oldani.
