### ISSUE TITLE
Partner adószám és kadószámtípus lehessen null a backenden

### ISSUE THREAD

**Issue by gyanyim** [flowacademyhu/iota-munkalap#203]
A Partner adószám és a kadószámtípus jelenleg kötelezően vár értéket, ezt át kell írni backenden, hogy null értéket is elfogadjon. Ez abban az esetben történjen, ha a partner magánszemély, akkor nem szükséges tárolni ezeket az adatokat.

**Comment by borosr** [comment]
Néhány egyéb javaslat a validáció fejlesztésére:

- nem nullcheckek kellenek a stringekre, hanem StringUtils.hasText-ek negálva, mert az vizsgál null-t is, meg üres stringet is
- ne legyen ennyire szétszeparálva, legyen minden a validate-be megírva és ha valami összetettebb vizsgálat, akkor azt csak az if-be hívd meg és csak boolean-t visszaadó függvényeket csinálj, de azok maguk ne dobjanak hibát
- taxNumberChecker - ez egy regex-szel megoldható, ne legyen for (amúgy a for tartalma meg egy NumberUtils-szel vizsgálható lenne) 
- bankAccountChecker - legyen regex-szel megoldva, legfeljebb 2-vel a hosszt vizsgálva (bár ez is megoldható a regexen belül)
- az email checker tartalma beköltözhet a validate-be, nem kell rá külön metódus, csak akkor legyen vizsgálva ha van a stringnek értéke
