### ISSUE TITLE
Partner létrehozása

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#21]
A partner lista oldalon legyen egy "Új partner" gomb, amit megnyomva egy új oldalra jutok, ahol a következő adatokat tudom megadni:

- számlázási név (kötelező)
- jogi személy vagy magánszemély
- adószám (kötelező, de csak ha jogi személy)
- számlázási címe a következő bontásban, külön mezőkben: ország, irányítószám, település, kerület, közterület neve, közterület jellege, házszám, épület, lépcsőház, szint, ajtó
- email (opcionális)
- telefon (opcionális)

A form alján legyen egy mentés gomb, ami validálás után beküldi az API-nak az adatokat. Sikeres API hívás esetén térjünk vissza a lista oldalra, sikertelen esetben jelenítsünk meg hibaüzenetet.

### Acceptance criteria
A form a fent leírt módon működik, ha még nincs kész API, akkor használjunk mockolt API-t.

**Comment by gyanyim** [comment]
@VicziTomi  instrukciója alapján így állítom be az adatokat: Kerulet, epulet, emelet, ajto (es azok amik valoban nem biztos hogy vannak) lehetnek null. Helyrajzi szam is lehet null.

**Comment by gyanyim** [comment]
Egyelőre a lépcsőházat is null-ra állíthatóra vettem.
