### ISSUE TITLE
HOTFIX: pdf

### ISSUE THREAD

**Issue by b-melani** [flowacademyhu/iota-munkalap#247]
A generált pdf-ben még nem jelennek meg a partner adatai.
Munkavégzés típusánál ha egyéb van kiválasztva, "egyéb egyéb + az egyéb szövege" jelenik meg. Elég lesz 1x is az egyéb.

**Comment by danielvarsas** [comment]
A módosítások készen vannak. Ellenőrizni háttérrendszer hiányában nem tudom.
