### ISSUE TITLE
Saját adatok módosítása munkavállalóként

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#26]
Legyen a menüben egy adataim menüpont, amire kattintva a felhasználó a saját adatait tudja szerkeszteni, amik a következőek:

- név
- email
- jelszó
- jelszó mégegyszer

A form végén legyen egy "Mentés" gomb, amire kattintva elküldjük az API-nak az adatokat.
A sikeres módosítás után jelenítsünk meg egy sikeres üzenetet és maradjunk az adott oldalon.
API hiba esetén jelenítsünk meg egy üzenetet, hogy nem sikerült módosítani az adatokat.

### Acceptance criteria
A form a fent leírt módon működjön. Validálás történjen az adatokra értelemszerűen. Ha nem ad meg jelszót, akkor azt ne frissítsük.

**Comment by VicziTomi** [comment]
wont do :(
