### ISSUE TITLE
Partnerhez tartozó munkalapok listázása

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#28]
A partnerek listában legyen a partnerek sorában egy ikon vagy gomb, amivel az adott partnerhez tartozó munkalap listára lehet ugrani.

### Acceptance criteria
Működik a gomb, a munkalap listára ugrik úgy, hogy az adott partnerre szűrünk.

**Comment by VicziTomi** [comment]
wont do :(
