### ISSUE TITLE
Munkalap rontása

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-munkalap#29]
A munkalap oldalán legyen egy "Rontott" gomb, amit megnyomva az adott munkalap rontottnak lesz jelölve.

### Acceptance criteria
A gomb megnyomására elmegy egy API kérés és a válasz eredményéről tájéköztatjuk üzenetben a felhasználót. Sikeres esetben térjünk vissza a lista oldalra.

@VicziTomi ez végül kell vagy sem?

**Comment by borosr** [comment]
Bátran!

**Comment by VicziTomi** [comment]
Zarom.
