### ISSUE TITLE
Új munkatárs gomb a munkatársak listája alá

### ISSUE THREAD

**Issue by Aniko-S** [flowacademyhu/iota-munkalap#46]
Legyen egy gomb a munkatársak listája alatt, amelyre kattintva arra az oldalra kerülünk, ahol új munkatársat hozhatunk létre.

**Comment by 6uliver** [comment]
@VicziTomi 
Ezek részletes átnézés nélkül lett bemergelve és lezárva ez: https://github.com/flowacademyhu/iota-munkalap/issues/5
Ennek a leírásában benne volt, hogy legyen gomb. Merge előtt alaposabban nézzük meg, hogy teljesenül-e a feladat leírása és AC-ja. Ilyen esetben jobb lenne, ha hiányosság van, hogy készül még egy PR ugyanahhoz az issue-hoz és nem zárjuk az issue-t, amíg nincs kész.

**Comment by VicziTomi** [comment]
Jogos, és bocsánat!

**Comment by VicziTomi** [comment]
Ez az issue szerintem zárható, mivel 'új munkatárs létrehozása' gomb és funkció megvalósult.
Melyik PR-en ment be? @Aniko-S
