### ISSUE TITLE
Munkalap készre jelentése

### ISSUE THREAD

**Issue by VicziTomi** [flowacademyhu/iota-munkalap#69]
Készíts egy `PUT /api/worsheets/finalize/{worksheet_id}` endpointot, ami path variable-ként megkapja a a munkalap id-ját és a státuszát 'Készre jelentett' állapotba állítja.
Az endpoint admin és munkavállaló felhasználó számára is elérhető.
Sikeres módosítás után térj vissza 200 response-val.

pliz check @borosr @akesztyus @karolyp

**Comment by 6uliver** [comment]
Nem tudom Springben mennyivel könnyíti a dolgot, viszont interface oldalról nézve sokkal logikusabb, ha a plusz művelet az ID után van, mivel a szerkesztés végpont is ilyen alakú: /api/worksheets/{worksheet_id} ezért ezután fűzve a műveletet szerintem jobb: /api/worksheets/{worksheet_id}/finalize
B megoldás, amit szoktak még, hogy nincs külön végpont, hanem a státusz is csak egy field, ami meghatározott logika alapján "szerkeszthető". Ez azért is jobb, mert lehet olyan use case, hogy szerkeszti és rögtön készre jelenti, ebben az esetben egy request menne így.
Ez az észrevételem a záráshoz is, de nem fogom oda is beírni.
